export const SET_SUPERHEROS = "SET_SUPERHEROS"
export const SET_SUPERHERO = "SET_SUPERHERO"
export const LOGGED = "LOGGED"
export const LOGOUT = "LOGOUT"
export const VIEW_USERS = "VIEW_USERS"
export const SEARCH_USERS = "SEARCH_USERS"
export const SEARCH_USER = "SEARCH_USER"
export const FAV_SUPERHERO = "FAV_SUPERHERO"